spring.application.name=mailsender

spring.datasource.url=jdbc:h2:mem:mail
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.mail.default-encoding=UTF-8
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.username=e886c677fa54a2
spring.mail.password=6c2461e10b8ed6
spring.mail.port=2525
spring.mail.protocol=smtp
spring.mail.test-connection=false
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
